const fs = require('fs');

const lesson1 = `
  'environmental-policy-governance': {
    lessonNumber: '23',
    title: 'Environmental Policy & Governance',
    subtitle: 'Discuss international agreements and regulations.',
    level: 'Band 7.0 - 8.5',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 23',
    sidebarLessonLabel: 'Lesson 23',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master environmental policy terms',
      'Discuss international agreements and regulations',
      'Analyze government environmental measures'
    ],
    words: [
      {
        word: 'regulation',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'a rule or directive made and maintained by an authority',
        instant: 'official rule',
        clue: 'Use it when talking about government laws that control business behavior to protect the environment.',
        pattern: 'environmental regulations / strict regulations',
        commonPattern: 'environmental regulations / strict regulations',
        example: 'Environmental regulations impose necessary limits on industrial emissions.',
        ieltsExample: 'Environmental regulations impose necessary limits on industrial emissions.',
        phrase: 'comply with regulations',
        warning: 'It refers to official rules, not just social expectations or guidelines.',
        confusionWarning: 'It refers to official rules, not just social expectations or guidelines.',
        useCases: ['government policy', 'business operations', 'pollution control', 'law'],
        mistake: {
          wrong: 'My mother made a regulation about bedtime.',
          right: 'The government introduced a new regulation on plastic waste.',
        },
        why: 'Regulation implies official, governmental, or institutional authority.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'subsidy',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'a sum of money granted by the government or a public body to assist an industry or business so that the price of a commodity or service may remain low or competitive',
        instant: 'government financial support',
        clue: 'Use it when the government pays money to help green energy become cheaper.',
        pattern: 'government subsidies / provide subsidies',
        commonPattern: 'government subsidies / provide subsidies',
        example: 'Subsidies for renewable energy accelerate the clean energy transition.',
        ieltsExample: 'Subsidies for renewable energy accelerate the clean energy transition.',
        phrase: 'receive a subsidy',
        warning: 'Subsidies lower costs; taxes increase them. Do not mix them up.',
        confusionWarning: 'Subsidies lower costs; taxes increase them. Do not mix them up.',
        useCases: ['economics', 'renewable energy', 'agriculture', 'government spending'],
        mistake: {
          wrong: 'The factory paid a subsidy to the government for polluting.',
          right: 'The factory paid a tax for polluting, but received a subsidy for installing solar panels.',
        },
        why: 'A subsidy is money given BY the government TO a business, not the other way around.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'enforcement',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the act of compelling observance of or compliance with a law, rule, or obligation',
        instant: 'making sure rules are followed',
        clue: 'Use it when talking about police, inspectors, or authorities catching people who break environmental laws.',
        pattern: 'strict enforcement / law enforcement',
        commonPattern: 'strict enforcement / law enforcement',
        example: 'Environmental enforcement ensures that corporations do not ignore pollution standards.',
        ieltsExample: 'Environmental enforcement ensures that corporations do not ignore pollution standards.',
        phrase: 'lack of enforcement',
        warning: 'It is the action of applying the law, not the law itself.',
        confusionWarning: 'It is the action of applying the law, not the law itself.',
        useCases: ['policing', 'legal systems', 'corporate accountability', 'government action'],
        mistake: {
          wrong: 'The enforcement is that you cannot litter.',
          right: 'The rule is that you cannot litter; enforcement requires police to fine litterbugs.',
        },
        why: 'Enforcement is the act of making people obey the rule.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'compliance',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the action or fact of complying with a wish or command',
        instant: 'following the rules',
        clue: 'Use it to describe when companies actually follow the environmental laws.',
        pattern: 'ensure compliance / strict compliance',
        commonPattern: 'ensure compliance / strict compliance',
        example: 'Environmental compliance monitoring tracks adherence to international regulations.',
        ieltsExample: 'Environmental compliance monitoring tracks adherence to international regulations.',
        phrase: 'in compliance with',
        warning: 'Do not use it as a verb. The verb is "comply".',
        confusionWarning: 'Do not use it as a verb. The verb is "comply".',
        useCases: ['business ethics', 'law', 'international agreements', 'auditing'],
        mistake: {
          wrong: 'The factory must compliance with the new rules.',
          right: 'The factory must ensure compliance with the new rules.',
        },
        why: 'Compliance is a noun; the verb form is comply.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Talking about official government rules?', answer: 'Use regulation.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Talking about government giving money to help an industry?', answer: 'Use subsidy.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Describing the act of making sure laws are obeyed?', answer: 'Use enforcement.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Describing the state of actually following those laws?', answer: 'Use compliance.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'To encourage people to buy electric cars, the government should offer a financial ______.',
        options: ['regulation', 'subsidy', 'compliance'],
        correct: 'subsidy',
        explanation: 'A subsidy is financial support provided by the government.',
      },
      {
        prompt: 'Having strict environmental laws is useless without proper ______ to catch offenders.',
        options: ['enforcement', 'subsidy', 'compliance'],
        correct: 'enforcement',
        explanation: 'Enforcement is the act of compelling people to obey the law.',
      },
      {
        prompt: 'Inspectors visit factories randomly to check their ______ with pollution standards.',
        options: ['compliance', 'enforcement', 'regulation'],
        correct: 'compliance',
        explanation: 'Compliance means the act of adhering to rules and regulations.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: 'The government makes a **regulation**. The police provide **enforcement**. The citizens show **compliance**.',
    },
    contrastTip: {
      title: 'Enforcement vs Compliance',
      text: '**Enforcement** is what the authorities do (making you follow rules). **Compliance** is what you do (following the rules).',
    },
    applyPrompt: 'Discuss how governments can force businesses to be more environmentally friendly.',
    applyHint: 'Aim to use: **regulation**, **enforcement**, and **compliance**.',
    modelAnswer:
      'Governments must establish strict environmental regulations backed by rigorous enforcement, ensuring that businesses maintain full compliance with pollution standards.',
    modelAnswerSegments: [
      { text: 'Governments must establish strict environmental ' },
      { text: 'regulations', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' backed by rigorous ' },
      { text: 'enforcement', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ', ensuring that businesses maintain full ' },
      { text: 'compliance', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' with pollution standards.' },
    ],
    modelBreakdown: [
      { term: 'regulations', text: 'referring to the official rules.' },
      { term: 'enforcement', text: 'describing the application of the law.' },
      { term: 'compliance', text: 'describing the adherence to the law by businesses.' },
    ],
    heroWordBubbles: [
      { label: 'regulation', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'subsidy', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'enforcement', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'compliance', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Practice using comply, compliance, and compliant.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'List ways governments can encourage green energy.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Match policies with their intended outcomes.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of the word subsidy.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss an environmental law in your country.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
  'urban-environment-smart-cities': {
    lessonNumber: '24',
    title: 'Urban Environment & Smart Cities',
    subtitle: 'Discuss sustainable city planning and urban challenges.',
    level: 'Band 6.5 - 8.0',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 24',
    sidebarLessonLabel: 'Lesson 24',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master 25 urban environment terms',
      'Discuss sustainable city planning',
      'Use smart city vocabulary accurately'
    ],
    words: [
      {
        word: 'sprawl',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the disorganized and uncontrolled expansion of an urban or industrial area into the adjoining countryside',
        instant: 'uncontrolled expansion',
        clue: 'Use it to describe cities that grow too wide, causing people to rely heavily on cars.',
        pattern: 'urban sprawl / suburban sprawl',
        commonPattern: 'urban sprawl / suburban sprawl',
        example: 'Urban sprawl contributes to increased car dependency and higher emissions.',
        ieltsExample: 'Urban sprawl contributes to increased car dependency and higher emissions.',
        phrase: 'combat urban sprawl',
        warning: 'It has a negative connotation, implying messy, unplanned growth.',
        confusionWarning: 'It has a negative connotation, implying messy, unplanned growth.',
        useCases: ['city planning', 'transportation', 'environmental impact', 'population growth'],
        mistake: {
          wrong: 'The city experienced beautiful urban sprawl.',
          right: 'The city is suffering from rapid urban sprawl.',
        },
        why: 'Sprawl is generally considered a negative phenomenon in urban planning.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'congestion',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the state of being crowded and full of traffic',
        instant: 'heavy traffic',
        clue: 'Use it instead of "traffic jam" for a more academic tone.',
        pattern: 'traffic congestion / relieve congestion',
        commonPattern: 'traffic congestion / relieve congestion',
        example: 'Public transportation reduces traffic congestion and improves air quality.',
        ieltsExample: 'Public transportation reduces traffic congestion and improves air quality.',
        phrase: 'ease traffic congestion',
        warning: 'It can also refer to a blocked nose (nasal congestion), but in IELTS it usually means traffic.',
        confusionWarning: 'It can also refer to a blocked nose (nasal congestion), but in IELTS it usually means traffic.',
        useCases: ['transportation', 'commuting', 'infrastructure', 'urban living'],
        mistake: {
          wrong: 'There were many congestions on the highway.',
          right: 'There was heavy congestion on the highway.',
        },
        why: 'Congestion is usually uncountable.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'infrastructure',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the basic physical and organizational structures and facilities (e.g. buildings, roads, power supplies) needed for the operation of a society',
        instant: 'basic facilities/systems',
        clue: 'Use it to refer to all the built systems a city needs to function (roads, bridges, internet, plumbing).',
        pattern: 'public infrastructure / cycling infrastructure',
        commonPattern: 'public infrastructure / cycling infrastructure',
        example: 'Investing in cycling infrastructure encourages sustainable commuting.',
        ieltsExample: 'Investing in cycling infrastructure encourages sustainable commuting.',
        phrase: 'upgrade the infrastructure',
        warning: 'It is almost always singular and uncountable.',
        confusionWarning: 'It is almost always singular and uncountable.',
        useCases: ['government spending', 'urban development', 'transport', 'economy'],
        mistake: {
          wrong: 'The city built many new infrastructures.',
          right: 'The city invested heavily in new infrastructure.',
        },
        why: 'Infrastructure is an uncountable noun.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'density',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the degree of compactness of a substance (or population)',
        instant: 'compactness / crowding',
        clue: 'Use "high-density housing" to describe tall apartment buildings that save space compared to spreading out.',
        pattern: 'high-density housing / population density',
        commonPattern: 'high-density housing / population density',
        example: 'High-density housing reduces land consumption and makes public transport more efficient.',
        ieltsExample: 'High-density housing reduces land consumption and makes public transport more efficient.',
        phrase: 'areas of high population density',
        warning: 'High density does not necessarily mean overcrowded; it just means many people in a smaller area (like a well-planned city center).',
        confusionWarning: 'High density does not necessarily mean overcrowded; it just means many people in a smaller area (like a well-planned city center).',
        useCases: ['urban planning', 'housing', 'demographics', 'public transport'],
        mistake: {
          wrong: 'The density of the traffic was very long.',
          right: 'The high population density makes a subway system necessary.',
        },
        why: 'Density refers to how tightly packed things are in a given space, not to length or volume.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Describing a city that spreads out too far?', answer: 'Use sprawl.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Describing roads full of cars?', answer: 'Use congestion.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Referring to roads, bridges, and public systems?', answer: 'Use infrastructure.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Describing areas where many people live close together?', answer: 'Use density.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'To solve traffic ______, the city must invest in better trains and buses.',
        options: ['sprawl', 'density', 'congestion'],
        correct: 'congestion',
        explanation: 'Congestion refers to roads being overly crowded with traffic.',
      },
      {
        prompt: 'Building high-______ apartment blocks is often better for the environment than building thousands of separate houses.',
        options: ['density', 'infrastructure', 'sprawl'],
        correct: 'density',
        explanation: 'High-density housing refers to many people living in a compact area, like high-rises.',
      },
      {
        prompt: 'When cities experience uncontrolled ______, natural habitats on the outskirts are destroyed to make room for suburbs.',
        options: ['sprawl', 'density', 'infrastructure'],
        correct: 'sprawl',
        explanation: 'Urban sprawl is the uncontrolled expansion of a city into the countryside.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Sprawl** goes outwards. **Density** goes upwards (like skyscrapers).',
    },
    contrastTip: {
      title: 'Congestion vs Traffic',
      text: '**Traffic** just means cars on the road (can be light or heavy). **Congestion** specifically means heavy, blocked traffic.',
    },
    applyPrompt: 'Discuss the benefits of building upwards rather than outwards in modern cities.',
    applyHint: 'Aim to use: **sprawl**, **density**, and **infrastructure**.',
    modelAnswer:
      'To prevent urban sprawl, cities should focus on high-density housing, which makes public transport infrastructure much more efficient and cost-effective.',
    modelAnswerSegments: [
      { text: 'To prevent urban ' },
      { text: 'sprawl', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ', cities should focus on high-' },
      { text: 'density', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' housing, which makes public transport ' },
      { text: 'infrastructure', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ' much more efficient and cost-effective.' },
    ],
    modelBreakdown: [
      { term: 'sprawl', text: 'referring to cities spreading outwards uncontrollably.' },
      { term: 'density', text: 'referring to compact, tall housing.' },
      { term: 'infrastructure', text: 'referring to the built systems like transport networks.' },
    ],
    heroWordBubbles: [
      { label: 'sprawl', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'congestion', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'infrastructure', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'density', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Practice using different forms of the word density.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'List ways to reduce traffic congestion.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Differentiate between infrastructure and buildings.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of the word sprawl.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Describe the transport infrastructure in your city.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
`;

const path = 'src/data/deepVocabularyLessons.ts';
let content = fs.readFileSync(path, 'utf8');

// find the last bracket
const lastIndex = content.lastIndexOf('};');
const newContent = content.slice(0, lastIndex) + lesson1 + content.slice(lastIndex);

fs.writeFileSync(path, newContent);
console.log('Batch 11 added.');
