const fs = require('fs');

const lesson1 = `
  'water-resources-ocean-conservation': {
    lessonNumber: '25',
    title: 'Water Resources & Ocean Conservation',
    subtitle: 'Discuss water scarcity and marine conservation.',
    level: 'Band 7.0 - 8.5',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 25',
    sidebarLessonLabel: 'Lesson 25',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master water and ocean terms',
      'Discuss water scarcity and management',
      'Use marine conservation vocabulary'
    ],
    words: [
      {
        word: 'scarcity',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the state of being scarce or in short supply; shortage',
        instant: 'short supply',
        clue: 'Use it when talking about regions that do not have enough fresh drinking water.',
        pattern: 'water scarcity / increasing scarcity',
        commonPattern: 'water scarcity / increasing scarcity',
        example: 'Water scarcity affects billions of people worldwide and threatens food security.',
        ieltsExample: 'Water scarcity affects billions of people worldwide and threatens food security.',
        phrase: 'combat water scarcity',
        warning: 'It means a severe shortage, not just a temporary lack of something.',
        confusionWarning: 'It means a severe shortage, not just a temporary lack of something.',
        useCases: ['resources', 'drought', 'global challenges', 'agriculture'],
        mistake: {
          wrong: 'There is a scarcity of milk in the fridge.',
          right: 'The region is suffering from severe water scarcity.',
        },
        why: 'Scarcity is usually reserved for large-scale economic or environmental shortages.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'desalination',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the process of removing salt from seawater to make it drinkable',
        instant: 'removing salt from water',
        clue: 'Use it when discussing technological solutions for countries with no fresh water.',
        pattern: 'desalination plants / process of desalination',
        commonPattern: 'desalination plants / process of desalination',
        example: 'Desalination plants convert seawater into freshwater for arid coastal regions.',
        ieltsExample: 'Desalination plants convert seawater into freshwater for arid coastal regions.',
        phrase: 'invest in desalination technology',
        warning: 'It applies only to saltwater; do not use it for cleaning dirty freshwater (which is purification).',
        confusionWarning: 'It applies only to saltwater; do not use it for cleaning dirty freshwater (which is purification).',
        useCases: ['technology', 'water supply', 'engineering solutions', 'arid regions'],
        mistake: {
          wrong: 'They used desalination to clean the muddy river.',
          right: 'They built a desalination plant by the ocean to provide drinking water.',
        },
        why: 'Desalination specifically means removing salt (saline) from seawater.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'deplete',
        part: 'verb',
        grammarRole: 'Verb',
        meaning: 'use up the supply or resources of',
        instant: 'use up entirely',
        clue: 'Use it when discussing overfishing or using up underground water supplies.',
        pattern: 'deplete resources / rapidly depleted',
        commonPattern: 'deplete resources / rapidly depleted',
        example: 'Overfishing has severely depleted fish stocks in many regions.',
        ieltsExample: 'Overfishing has severely depleted fish stocks in many regions.',
        phrase: 'depletion of natural resources',
        warning: 'It means to reduce the amount significantly, often to a dangerous level.',
        confusionWarning: 'It means to reduce the amount significantly, often to a dangerous level.',
        useCases: ['fishing', 'groundwater', 'fossil fuels', 'environmental damage'],
        mistake: {
          wrong: 'I depleted my glass of water.',
          right: 'Industrial farming has depleted the local aquifer.',
        },
        why: 'Deplete is used for large-scale resources, not everyday single items.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'bleaching',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the process of turning white or pale (specifically coral expelling algae due to stress)',
        instant: 'turning white and dying',
        clue: 'Use "coral bleaching" to describe the effect of warming oceans on reefs.',
        pattern: 'coral bleaching / mass bleaching events',
        commonPattern: 'coral bleaching / mass bleaching events',
        example: 'Coral bleaching occurs when rising ocean temperatures cause corals to expel their algae.',
        ieltsExample: 'Coral bleaching occurs when rising ocean temperatures cause corals to expel their algae.',
        phrase: 'widespread coral bleaching',
        warning: 'In an environmental context, it almost exclusively refers to coral reefs.',
        confusionWarning: 'In an environmental context, it almost exclusively refers to coral reefs.',
        useCases: ['marine biology', 'climate change', 'oceans', 'global warming impacts'],
        mistake: {
          wrong: 'The fish suffered from bleaching.',
          right: 'The Great Barrier Reef is suffering from severe coral bleaching.',
        },
        why: 'Bleaching in this context is specific to corals losing their symbiotic algae.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Describing a severe lack of fresh water?', answer: 'Use scarcity.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Talking about turning seawater into drinking water?', answer: 'Use desalination.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Describing the using up of fish or water resources?', answer: 'Use deplete.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Talking about coral reefs dying and turning white?', answer: 'Use bleaching.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'To combat water ______, coastal cities are investing heavily in new technologies.',
        options: ['deplete', 'scarcity', 'bleaching'],
        correct: 'scarcity',
        explanation: 'Water scarcity refers to a severe lack of water.',
      },
      {
        prompt: 'Overfishing continues to ______ marine populations around the world.',
        options: ['deplete', 'desalination', 'scarcity'],
        correct: 'deplete',
        explanation: 'To deplete means to exhaust or drastically reduce the supply of a resource.',
      },
      {
        prompt: 'Engineers have built massive ______ plants to convert ocean water into fresh water.',
        options: ['deplete', 'bleaching', 'desalination'],
        correct: 'desalination',
        explanation: 'Desalination is the process of removing salt from seawater.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**De-salin-ation**: De (remove) + saline (salt).',
    },
    contrastTip: {
      title: 'Scarcity vs Shortage',
      text: 'A **shortage** can be temporary (a fuel shortage this week). **Scarcity** implies a fundamental, long-term lack of a resource.',
    },
    applyPrompt: 'Discuss the major threats facing our oceans and fresh water supplies today.',
    applyHint: 'Aim to use: **scarcity**, **deplete**, and **bleaching**.',
    modelAnswer:
      'Climate change is driving severe water scarcity on land, while warming oceans cause coral bleaching and overfishing continues to deplete marine life.',
    modelAnswerSegments: [
      { text: 'Climate change is driving severe water ' },
      { text: 'scarcity', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' on land, while warming oceans cause coral ' },
      { text: 'bleaching', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' and overfishing continues to ' },
      { text: 'deplete', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ' marine life.' },
    ],
    modelBreakdown: [
      { term: 'scarcity', text: 'describing the extreme shortage of freshwater.' },
      { term: 'bleaching', text: 'referring to the dying of coral reefs.' },
      { term: 'deplete', text: 'describing the using up of fish populations.' },
    ],
    heroWordBubbles: [
      { label: 'scarcity', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'desalination', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'deplete', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'bleaching', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Practice using deplete, depletion, and depleted.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'List solutions to global water scarcity.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Match marine problems with their causes.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of the word desalination.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss how your country manages water resources.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
  'artificial-intelligence-automation': {
    lessonNumber: '26',
    title: 'Artificial Intelligence & Automation',
    subtitle: 'Discuss AI, machine learning, and technological impacts.',
    level: 'Band 7.0 - 8.5',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 26',
    sidebarLessonLabel: 'Lesson 26',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master AI and automation terms',
      'Discuss technological impacts on society',
      'Use technical vocabulary accurately'
    ],
    words: [
      {
        word: 'automation',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the use of largely automatic equipment in a system of manufacturing or other production process',
        instant: 'machines doing human work',
        clue: 'Use it when talking about robots or computers replacing human jobs in factories or offices.',
        pattern: 'increasing automation / automation of jobs',
        commonPattern: 'increasing automation / automation of jobs',
        example: 'Automation threatens to displace workers in routine and repetitive occupations.',
        ieltsExample: 'Automation threatens to displace workers in routine and repetitive occupations.',
        phrase: 'the rise of automation',
        warning: 'It refers to the process itself, not to the physical robots.',
        confusionWarning: 'It refers to the process itself, not to the physical robots.',
        useCases: ['employment', 'manufacturing', 'future of work', 'technology'],
        mistake: {
          wrong: 'The factory bought a new automation.',
          right: 'The factory increased its level of automation.',
        },
        why: 'Automation is the abstract concept or process, not a physical machine.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'autonomous',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: 'having the freedom to act independently; (of a vehicle) navigating and driving without human input',
        instant: 'self-operating',
        clue: 'Use it when talking about self-driving cars or independent AI systems.',
        pattern: 'autonomous vehicles / fully autonomous',
        commonPattern: 'autonomous vehicles / fully autonomous',
        example: 'Autonomous vehicles could revolutionize transportation by reducing human error.',
        ieltsExample: 'Autonomous vehicles could revolutionize transportation by reducing human error.',
        phrase: 'development of autonomous technology',
        warning: 'Do not confuse with automatic (which means doing a set task without thinking); autonomous implies making independent decisions.',
        confusionWarning: 'Do not confuse with automatic (which means doing a set task without thinking); autonomous implies making independent decisions.',
        useCases: ['transportation', 'robotics', 'AI ethics', 'military technology'],
        mistake: {
          wrong: 'My toaster is autonomous.',
          right: 'The new drone is fully autonomous.',
        },
        why: 'A toaster is automatic; it cannot make independent navigation or operational decisions.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'algorithm',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'a process or set of rules to be followed in calculations or other problem-solving operations, especially by a computer',
        instant: 'computer rules/instructions',
        clue: 'Use it to describe the hidden math that decides what you see on social media or how an AI learns.',
        pattern: 'complex algorithms / social media algorithms',
        commonPattern: 'complex algorithms / social media algorithms',
        example: 'Machine learning algorithms improve themselves automatically through experience and data.',
        ieltsExample: 'Machine learning algorithms improve themselves automatically through experience and data.',
        phrase: 'driven by an algorithm',
        warning: 'It is a specific computer science term; do not use it to just mean a "plan" or "idea".',
        confusionWarning: 'It is a specific computer science term; do not use it to just mean a "plan" or "idea".',
        useCases: ['social media', 'machine learning', 'data privacy', 'technology'],
        mistake: {
          wrong: 'My algorithm for baking a cake is simple.',
          right: 'The app uses a sophisticated algorithm to recommend songs.',
        },
        why: 'While technically a recipe is an algorithm, in everyday and academic English it almost exclusively refers to computers.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'bias',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'prejudice in favor of or against one thing, person, or group compared with another, usually in a way considered to be unfair',
        instant: 'unfair prejudice',
        clue: 'Use "algorithmic bias" to discuss how AI can accidentally become racist or sexist based on bad training data.',
        pattern: 'algorithmic bias / human bias',
        commonPattern: 'algorithmic bias / human bias',
        example: 'Algorithmic bias can perpetuate discrimination if AI models are trained on flawed data.',
        ieltsExample: 'Algorithmic bias can perpetuate discrimination if AI models are trained on flawed data.',
        phrase: 'unconscious bias in AI',
        warning: 'Bias is a noun; the adjective is "biased". Do not say "the AI is bias".',
        confusionWarning: 'Bias is a noun; the adjective is "biased". Do not say "the AI is bias".',
        useCases: ['AI ethics', 'facial recognition', 'hiring software', 'social justice'],
        mistake: {
          wrong: 'The computer program is very bias.',
          right: 'The computer program exhibits algorithmic bias.',
        },
        why: 'You must use the noun form (bias) or the adjective form (biased).',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Talking about machines replacing human workers?', answer: 'Use automation.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Describing a car or drone that drives itself?', answer: 'Use autonomous.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Talking about the mathematical rules running an AI?', answer: 'Use algorithm.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Discussing unfair decisions made by computers?', answer: 'Use bias (algorithmic bias).', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'The transition to ______ vehicles will require major changes to city infrastructure.',
        options: ['algorithm', 'autonomous', 'bias'],
        correct: 'autonomous',
        explanation: 'Autonomous refers to vehicles that drive themselves independently.',
      },
      {
        prompt: 'Social media platforms use a complex ______ to decide which posts appear on your feed.',
        options: ['algorithm', 'automation', 'autonomous'],
        correct: 'algorithm',
        explanation: 'An algorithm is a set of rules a computer follows to make calculations or decisions.',
      },
      {
        prompt: 'Increased ______ in manufacturing has led to a significant loss of traditional factory jobs.',
        options: ['automation', 'bias', 'autonomous'],
        correct: 'automation',
        explanation: 'Automation is the process of replacing human labor with machines.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Autonomous** = Auto (self) + nomos (law) = self-governing.',
    },
    contrastTip: {
      title: 'Automatic vs Autonomous',
      text: 'An **automatic** door just opens when you step on a mat. An **autonomous** robot decides which door to open based on its goal.',
    },
    applyPrompt: 'Discuss the potential dangers of relying too heavily on artificial intelligence.',
    applyHint: 'Aim to use: **autonomous**, **algorithm**, and **bias**.',
    modelAnswer:
      'If we rely entirely on autonomous systems run by flawed algorithms, we risk perpetuating algorithmic bias that can unfairly discriminate against certain groups.',
    modelAnswerSegments: [
      { text: 'If we rely entirely on ' },
      { text: 'autonomous', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' systems run by flawed ' },
      { text: 'algorithms', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ', we risk perpetuating algorithmic ' },
      { text: 'bias', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' that can unfairly discriminate against certain groups.' },
    ],
    modelBreakdown: [
      { term: 'autonomous', text: 'describing independent, self-operating systems.' },
      { term: 'algorithms', text: 'referring to the computer code and rules.' },
      { term: 'bias', text: 'describing the unfair prejudice in the AI.' },
    ],
    heroWordBubbles: [
      { label: 'automation', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'autonomous', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'algorithm', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'bias', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Practice using autonomous and autonomy.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'List jobs that might be lost to automation.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Identify examples of algorithmic bias.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of the word algorithm.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss how AI affects your daily life.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
`;

const path = 'src/data/deepVocabularyLessons.ts';
let content = fs.readFileSync(path, 'utf8');

// find the last bracket
const lastIndex = content.lastIndexOf('};');
const newContent = content.slice(0, lastIndex) + lesson1 + content.slice(lastIndex);

fs.writeFileSync(path, newContent);
console.log('Batch 12 added.');
