const fs = require('fs');

const lesson1 = `
  'digital-communication-social-media': {
    lessonNumber: '27',
    title: 'Digital Communication & Social Media',
    subtitle: 'Discuss social media impacts and online culture.',
    level: 'Band 6.5 - 8.0',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 27',
    sidebarLessonLabel: 'Lesson 27',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master digital communication terms',
      'Discuss social media impacts',
      'Use online culture vocabulary'
    ],
    words: [
      {
        word: 'literacy',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'competence or knowledge in a specified area (e.g., digital literacy)',
        instant: 'ability to understand/use',
        clue: 'Use "digital literacy" when talking about teaching people how to spot fake news or use computers safely.',
        pattern: 'digital literacy / media literacy',
        commonPattern: 'digital literacy / media literacy',
        example: 'Digital literacy is essential for navigating online information and avoiding scams.',
        ieltsExample: 'Digital literacy is essential for navigating online information and avoiding scams.',
        phrase: 'improve digital literacy skills',
        warning: 'While it traditionally means the ability to read and write, in IELTS Technology questions, it usually pairs with "digital" or "media".',
        confusionWarning: 'While it traditionally means the ability to read and write, in IELTS Technology questions, it usually pairs with "digital" or "media".',
        useCases: ['education', 'internet safety', 'social media', 'critical thinking'],
        mistake: {
          wrong: 'He has a high literacy of computers.',
          right: 'He has a high level of digital literacy.',
        },
        why: 'Literacy in this context is almost always preceded by an adjective like digital, computer, or media.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'viral',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: 'an image, video, or piece of information that is circulated rapidly and widely from one internet user to another',
        instant: 'spreading rapidly online',
        clue: 'Use it to describe how fast a rumor, meme, or news story spreads on social media.',
        pattern: 'go viral / viral content',
        commonPattern: 'go viral / viral content',
        example: 'Viral content can reach millions of users within hours, making it difficult to control.',
        ieltsExample: 'Viral content can reach millions of users within hours, making it difficult to control.',
        phrase: 'the video went viral',
        warning: 'It can also relate to diseases (a viral infection). Context is key.',
        confusionWarning: 'It can also relate to diseases (a viral infection). Context is key.',
        useCases: ['social media', 'marketing', 'fake news', 'trends'],
        mistake: {
          wrong: 'The news viraled quickly.',
          right: 'The news went viral quickly.',
        },
        why: 'Viral is an adjective. The verb phrase is "to go viral".',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'misinformation',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'false or inaccurate information, especially that which is deliberately intended to deceive',
        instant: 'false information',
        clue: 'Use it instead of "fake news" for a more academic, formal tone in your essays.',
        pattern: 'spread of misinformation / combat misinformation',
        commonPattern: 'spread of misinformation / combat misinformation',
        example: 'Misinformation spreads rapidly through social networks, influencing public opinion.',
        ieltsExample: 'Misinformation spreads rapidly through social networks, influencing public opinion.',
        phrase: 'a campaign of misinformation',
        warning: 'It is an uncountable noun. Do not say "misinformations".',
        confusionWarning: 'It is an uncountable noun. Do not say "misinformations".',
        useCases: ['politics', 'health', 'social media', 'journalism'],
        mistake: {
          wrong: 'There are many misinformations on the internet.',
          right: 'There is a lot of misinformation on the internet.',
        },
        why: 'Misinformation is uncountable.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'footprint',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the trail of data you create while using the internet (digital footprint)',
        instant: 'online data trail',
        clue: 'Use "digital footprint" when discussing online privacy or how employers check social media.',
        pattern: 'digital footprint / leave a footprint',
        commonPattern: 'digital footprint / leave a footprint',
        example: 'Digital footprints are permanent records of online activity that can affect future job prospects.',
        ieltsExample: 'Digital footprints are permanent records of online activity that can affect future job prospects.',
        phrase: 'reduce your digital footprint',
        warning: 'In IELTS, it is also used for "carbon footprint". Always specify "digital footprint" when talking about the internet.',
        confusionWarning: 'In IELTS, it is also used for "carbon footprint". Always specify "digital footprint" when talking about the internet.',
        useCases: ['privacy', 'cybersecurity', 'social media', 'employment'],
        mistake: {
          wrong: 'Be careful of your footprint online.',
          right: 'Be careful of your digital footprint.',
        },
        why: 'You must specify "digital" so the examiner knows you are not talking about carbon emissions.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Talking about teaching people how to use the internet safely?', answer: 'Use digital literacy.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Describing content spreading incredibly fast?', answer: 'Use viral.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'A formal word for fake news and lies online?', answer: 'Use misinformation.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'The trail of personal data left online?', answer: 'Use digital footprint.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'To combat ______, schools must teach students how to verify their sources.',
        options: ['viral', 'literacy', 'misinformation'],
        correct: 'misinformation',
        explanation: 'Misinformation refers to false or inaccurate information.',
      },
      {
        prompt: 'Every time you post a photo or like a page, you are adding to your digital ______.',
        options: ['footprint', 'viral', 'literacy'],
        correct: 'footprint',
        explanation: 'A digital footprint is the trail of data left by online activity.',
      },
      {
        prompt: 'It only takes one controversial tweet for a politician\'s mistake to go ______.',
        options: ['literacy', 'misinformation', 'viral'],
        correct: 'viral',
        explanation: 'Going viral means spreading rapidly and widely across the internet.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: 'You need **digital literacy** (reading skills) to avoid **misinformation** (fake text) and protect your **digital footprint** (your tracks).',
    },
    contrastTip: {
      title: 'Misinformation vs Disinformation',
      text: '**Misinformation** is false information shared accidentally. **Disinformation** is false information shared intentionally to deceive.',
    },
    applyPrompt: 'Discuss the challenges children face when using social media unmonitored.',
    applyHint: 'Aim to use: **misinformation**, **viral**, and **literacy**.',
    modelAnswer:
      'Without proper digital literacy, children are highly vulnerable to believing misinformation, especially when dangerous trends go viral on social media platforms.',
    modelAnswerSegments: [
      { text: 'Without proper digital ' },
      { text: 'literacy', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ', children are highly vulnerable to believing ' },
      { text: 'misinformation', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ', especially when dangerous trends go ' },
      { text: 'viral', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' on social media platforms.' },
    ],
    modelBreakdown: [
      { term: 'literacy', text: 'referring to the ability to navigate digital media.' },
      { term: 'misinformation', text: 'describing the false content.' },
      { term: 'viral', text: 'describing the rapid spread.' },
    ],
    heroWordBubbles: [
      { label: 'literacy', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'viral', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'misinformation', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'footprint', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Practice using inform, misinform, and misinformation.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'List ways to protect privacy online.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Match digital concepts with their real-world equivalents.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of the word viral.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss a time you saw false news online.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
  'cybersecurity-data-protection': {
    lessonNumber: '28',
    title: 'Cybersecurity & Data Protection',
    subtitle: 'Discuss online security, privacy, and data protection.',
    level: 'Band 7.0 - 8.5',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 28',
    sidebarLessonLabel: 'Lesson 28',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master cybersecurity terms',
      'Discuss data privacy and protection',
      'Use security vocabulary accurately'
    ],
    words: [
      {
        word: 'breach',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'an act of breaking or failing to observe a law, agreement, or code of conduct (data breach: unauthorized access to data)',
        instant: 'security failure / leak',
        clue: 'Use "data breach" when talking about hackers stealing millions of passwords or credit cards.',
        pattern: 'data breach / security breach',
        commonPattern: 'data breach / security breach',
        example: 'Major data breaches expose sensitive personal information to cybercriminals.',
        ieltsExample: 'Major data breaches expose sensitive personal information to cybercriminals.',
        phrase: 'suffer a data breach',
        warning: 'It implies that a barrier or defense has been broken.',
        confusionWarning: 'It implies that a barrier or defense has been broken.',
        useCases: ['cybersecurity', 'banking', 'privacy', 'corporate responsibility'],
        mistake: {
          wrong: 'The hacker made a data steal.',
          right: 'The hacker caused a massive data breach.',
        },
        why: 'Data breach is the standard professional terminology.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'encryption',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the process of converting information or data into a code, especially to prevent unauthorized access',
        instant: 'scrambling data for security',
        clue: 'Use it when talking about how messaging apps (like WhatsApp) keep conversations private.',
        pattern: 'end-to-end encryption / data encryption',
        commonPattern: 'end-to-end encryption / data encryption',
        example: 'Encryption protects data by converting it into unreadable code during transmission.',
        ieltsExample: 'Encryption protects data by converting it into unreadable code during transmission.',
        phrase: 'use strong encryption',
        warning: 'It refers to the protective scrambling process, not the password itself.',
        confusionWarning: 'It refers to the protective scrambling process, not the password itself.',
        useCases: ['technology', 'privacy', 'government surveillance', 'banking'],
        mistake: {
          wrong: 'I put an encryption on my phone.',
          right: 'I enabled encryption on my phone.',
        },
        why: 'Encryption is an uncountable process or system.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'malware',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'software that is specifically designed to disrupt, damage, or gain unauthorized access to a computer system',
        instant: 'malicious software (viruses)',
        clue: 'Use it as a broader, more academic term than "computer virus".',
        pattern: 'malware attack / install malware',
        commonPattern: 'malware attack / install malware',
        example: 'Malware includes viruses, ransomware, and spyware designed to cause harm.',
        ieltsExample: 'Malware includes viruses, ransomware, and spyware designed to cause harm.',
        phrase: 'infected with malware',
        warning: 'It is an uncountable noun. Do not say "malwares".',
        confusionWarning: 'It is an uncountable noun. Do not say "malwares".',
        useCases: ['cybercrime', 'IT security', 'internet safety', 'technology'],
        mistake: {
          wrong: 'My computer has many malwares.',
          right: 'My computer is infected with malware.',
        },
        why: 'Malware is an uncountable noun (like software).',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'phishing',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the fraudulent practice of sending emails purporting to be from reputable companies in order to induce individuals to reveal personal information',
        instant: 'scam emails',
        clue: 'Use it to describe scams where criminals pretend to be a bank or delivery company to steal passwords.',
        pattern: 'phishing scams / phishing attacks',
        commonPattern: 'phishing scams / phishing attacks',
        example: 'Phishing attacks trick users into revealing personal information like banking passwords.',
        ieltsExample: 'Phishing attacks trick users into revealing personal information like banking passwords.',
        phrase: 'fall victim to a phishing scam',
        warning: 'Do not confuse with "fishing" (catching fish), though the metaphor (using bait to catch a victim) is identical.',
        confusionWarning: 'Do not confuse with "fishing" (catching fish), though the metaphor (using bait to catch a victim) is identical.',
        useCases: ['cybercrime', 'fraud', 'digital literacy', 'security awareness'],
        mistake: {
          wrong: 'He lost money because of fishing.',
          right: 'He lost money because of a phishing attack.',
        },
        why: 'Phishing is spelled with a "ph" to refer to the cybercrime.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Describing a massive leak of customer data?', answer: 'Use data breach.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Talking about scrambling messages so hackers cannot read them?', answer: 'Use encryption.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'A formal word for viruses and spyware?', answer: 'Use malware.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Talking about fake emails designed to steal passwords?', answer: 'Use phishing.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'To protect customer privacy, messaging apps use end-to-end ______.',
        options: ['breach', 'encryption', 'phishing'],
        correct: 'encryption',
        explanation: 'Encryption converts information into a secret code.',
      },
      {
        prompt: 'If you click a link in a suspicious email, you might accidentally download ______.',
        options: ['phishing', 'breach', 'malware'],
        correct: 'malware',
        explanation: 'Malware is malicious software designed to harm a computer.',
      },
      {
        prompt: 'The bank suffered a massive security ______ and millions of credit card numbers were stolen.',
        options: ['breach', 'encryption', 'malware'],
        correct: 'breach',
        explanation: 'A security or data breach is an incident where data is accessed without authorization.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Mal** means bad (malware = bad software). **Phishing** uses fake "bait" (emails) to catch your passwords.',
    },
    contrastTip: {
      title: 'Malware vs Phishing',
      text: '**Malware** attacks your computer\'s system. **Phishing** attacks human psychology (tricking you).',
    },
    applyPrompt: 'Discuss the importance of teaching older generations about internet safety.',
    applyHint: 'Aim to use: **phishing**, **malware**, and **breach**.',
    modelAnswer:
      'Older adults must be taught to recognize phishing emails to avoid inadvertently downloading malware, which could lead to a devastating breach of their personal finances.',
    modelAnswerSegments: [
      { text: 'Older adults must be taught to recognize ' },
      { text: 'phishing', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' emails to avoid inadvertently downloading ' },
      { text: 'malware', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ', which could lead to a devastating ' },
      { text: 'breach', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' of their personal finances.' },
    ],
    modelBreakdown: [
      { term: 'phishing', text: 'describing the scam emails used as bait.' },
      { term: 'malware', text: 'referring to the dangerous software.' },
      { term: 'breach', text: 'describing the unauthorized access to data.' },
    ],
    heroWordBubbles: [
      { label: 'breach', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'encryption', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'malware', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'phishing', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Practice using encrypt and encryption.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'List ways to prevent cybercrime.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Match the threat to the defense.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of the word malware.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss how you protect your personal data online.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
`;

const path = 'src/data/deepVocabularyLessons.ts';
let content = fs.readFileSync(path, 'utf8');

// find the last bracket
const lastIndex = content.lastIndexOf('};');
const newContent = content.slice(0, lastIndex) + lesson1 + content.slice(lastIndex);

fs.writeFileSync(path, newContent);
console.log('Batch 13 added.');
