const fs = require('fs');

const lesson1 = `
  'climate-change-causes-effects': {
    lessonNumber: '19',
    title: 'Climate Change: Causes & Effects',
    subtitle: 'Discuss causes and effects of global warming accurately.',
    level: 'Band 7.0 - 8.5',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 19',
    sidebarLessonLabel: 'Lesson 19',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master climate change terms for sophisticated discussions',
      'Discuss causes and effects of global warming accurately',
      'Use scientific vocabulary naturally in essays'
    ],
    words: [
      {
        word: 'anthropogenic',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: 'caused or produced by humans (especially environmental pollution and pollutants)',
        instant: 'human-caused',
        clue: 'Use it instead of "human-made" when discussing climate change scientifically.',
        pattern: 'anthropogenic climate change / anthropogenic emissions',
        commonPattern: 'anthropogenic climate change / anthropogenic emissions',
        example: 'Greenhouse gas emissions are the primary driver of anthropogenic climate change.',
        ieltsExample: 'Greenhouse gas emissions are the primary driver of anthropogenic climate change.',
        phrase: 'the impact of anthropogenic activities',
        warning: 'It is a highly formal scientific term; do not use it for everyday human activities like cooking or building.',
        confusionWarning: 'It is a highly formal scientific term; do not use it for everyday human activities like cooking or building.',
        useCases: ['climate change', 'pollution', 'environmental impact', 'global warming'],
        mistake: {
          wrong: 'The factory is an anthropogenic building.',
          right: 'The factory contributes to anthropogenic pollution.',
        },
        why: 'Anthropogenic specifically refers to environmental effects caused by humans.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'footprint',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the impact on the environment left by a person, organization, or community, often measured in carbon emissions',
        instant: 'environmental impact mark',
        clue: 'Use it when talking about reducing the amount of damage or emissions a country or person produces.',
        pattern: 'carbon footprint / ecological footprint',
        commonPattern: 'carbon footprint / ecological footprint',
        example: 'The carbon footprint of developed nations far exceeds that of developing countries.',
        ieltsExample: 'The carbon footprint of developed nations far exceeds that of developing countries.',
        phrase: 'reduce our carbon footprint',
        warning: 'In this context, it rarely means a physical footprint on the ground.',
        confusionWarning: 'In this context, it rarely means a physical footprint on the ground.',
        useCases: ['carbon emissions', 'sustainability', 'environmental impact', 'personal responsibility'],
        mistake: {
          wrong: 'The factory left a big footprint on the grass.',
          right: 'The factory left a massive carbon footprint on the environment.',
        },
        why: 'In IELTS essays, footprint usually collocates with carbon or ecological.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'mitigate',
        part: 'verb',
        grammarRole: 'Verb',
        meaning: 'make (something bad) less severe, harmful, or painful',
        instant: 'make less severe',
        clue: 'Use it when discussing solutions that reduce the intensity of a problem, even if they don\\'t solve it completely.',
        pattern: 'mitigate the effects of / mitigate climate change',
        commonPattern: 'mitigate the effects of / mitigate climate change',
        example: 'We need to mitigate climate change through emission reductions while adapting to its inevitable impacts.',
        ieltsExample: 'We need to mitigate climate change through emission reductions while adapting to its inevitable impacts.',
        phrase: 'take steps to mitigate',
        warning: 'Do not confuse it with mediate (to settle a dispute).',
        confusionWarning: 'Do not confuse it with mediate (to settle a dispute).',
        useCases: ['climate change', 'pollution', 'disaster response', 'risk management'],
        mistake: {
          wrong: 'We must mitigate the broken window.',
          right: 'We must mitigate the effects of the storm.',
        },
        why: 'Mitigate applies to abstract negative effects or situations, not physical objects.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'consensus',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'a general agreement among a group of experts or people',
        instant: 'general agreement',
        clue: 'Use it to show that a scientific fact is widely accepted and not seriously debated.',
        pattern: 'scientific consensus / reach a consensus',
        commonPattern: 'scientific consensus / reach a consensus',
        example: 'The scientific consensus on human-caused climate change is now overwhelming.',
        ieltsExample: 'The scientific consensus on human-caused climate change is now overwhelming.',
        phrase: 'a broad consensus that',
        warning: 'Do not say "a general consensus" as it is somewhat repetitive; consensus already implies it is general.',
        confusionWarning: 'Do not say "a general consensus" as it is somewhat repetitive; consensus already implies it is general.',
        useCases: ['scientific research', 'policy making', 'global agreements', 'expert opinions'],
        mistake: {
          wrong: 'The scientists had a consensus about their lunch.',
          right: 'There is a strong scientific consensus on global warming.',
        },
        why: 'Consensus is a formal word used for serious, widespread agreement, usually among experts.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Talking about things caused by humans?', answer: 'Use anthropogenic.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Referring to your environmental impact?', answer: 'Use footprint.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Discussing ways to make a problem less severe?', answer: 'Use mitigate.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Talking about scientists agreeing on a fact?', answer: 'Use consensus.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'To slow down global warming, every nation must take action to reduce its carbon ______.',
        options: ['footprint', 'consensus', 'mitigate'],
        correct: 'footprint',
        explanation: 'Carbon footprint refers to the amount of greenhouse gases produced.',
      },
      {
        prompt: 'There is a clear scientific ______ that sea levels are rising at an alarming rate.',
        options: ['anthropogenic', 'consensus', 'footprint'],
        correct: 'consensus',
        explanation: 'A general agreement among scientists is a scientific consensus.',
      },
      {
        prompt: 'Which word best describes efforts to plant trees to make the effects of carbon emissions less severe?',
        options: ['mitigate', 'anthropogenic', 'consensus'],
        correct: 'mitigate',
        explanation: 'To mitigate means to reduce the severity of a negative impact.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Mitigate** = make milder. **Anthropogenic** = Anthro (human) + genic (produced).',
    },
    contrastTip: {
      title: 'Mitigate vs Prevent',
      text: '**Prevent** means stopping something completely before it happens. **Mitigate** means making it less damaging after it starts.',
    },
    applyPrompt: 'Discuss how human activities affect the climate and what can be done to lessen the damage.',
    applyHint: 'Aim to use: **anthropogenic**, **footprint**, and **mitigate**.',
    modelAnswer:
      'Given the scientific consensus on anthropogenic climate change, individuals must reduce their carbon footprint while governments invest in renewable energy to mitigate the long-term effects.',
    modelAnswerSegments: [
      { text: 'Given the scientific ' },
      { text: 'consensus', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' on ' },
      { text: 'anthropogenic', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' climate change, individuals must reduce their carbon ' },
      { text: 'footprint', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' while governments invest in renewable energy to ' },
      { text: 'mitigate', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ' the long-term effects.' },
    ],
    modelBreakdown: [
      { term: 'consensus', text: 'referencing the agreement among experts.' },
      { term: 'anthropogenic', text: 'specifying human-caused change.' },
      { term: 'footprint', text: 'referring to environmental impact.' },
      { term: 'mitigate', text: 'describing the reduction of harm.' },
    ],
    heroWordBubbles: [
      { label: 'anthropogenic', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'footprint', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'mitigate', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'consensus', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Combine words to form accurate scientific collocations.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'Write an introduction about the causes of global warming.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Differentiate between mitigate, adapt, and prevent.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of advanced environmental terms.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Explain how you try to reduce your environmental impact.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
  'sustainability-green-solutions': {
    lessonNumber: '20',
    title: 'Sustainability & Green Solutions',
    subtitle: 'Discuss environmental solutions and renewable energy.',
    level: 'Band 6.5 - 8.0',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 20',
    sidebarLessonLabel: 'Lesson 20',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master sustainability and green technology terms',
      'Discuss environmental solutions confidently',
      'Use renewable energy vocabulary accurately'
    ],
    words: [
      {
        word: 'renewable',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: 'capable of being replenished naturally over a short period of time',
        instant: 'naturally replenished',
        clue: 'Use it when discussing energy sources that never run out, like wind or solar.',
        pattern: 'renewable energy / renewable resources',
        commonPattern: 'renewable energy / renewable resources',
        example: 'Renewable energy sources such as solar and wind power are becoming increasingly cost-effective.',
        ieltsExample: 'Renewable energy sources such as solar and wind power are becoming increasingly cost-effective.',
        phrase: 'transition to renewable energy',
        warning: 'Do not confuse it with recyclable; renewable applies to natural resources that replenish themselves.',
        confusionWarning: 'Do not confuse it with recyclable; renewable applies to natural resources that replenish themselves.',
        useCases: ['energy transition', 'solar power', 'wind power', 'government policy'],
        mistake: {
          wrong: 'We should use more renewable plastic bottles.',
          right: 'We should rely more on renewable energy.',
        },
        why: 'Renewable is generally used for energy and resources, whereas plastic bottles are recyclable or reusable.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'sustainable',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: 'able to be maintained at a certain rate or level without depleting natural resources',
        instant: 'able to continue long-term',
        clue: 'Use it when describing practices that protect the future, like agriculture, development, or lifestyle.',
        pattern: 'sustainable development / sustainable practices',
        commonPattern: 'sustainable development / sustainable practices',
        example: 'Sustainable development meets present needs without compromising the ability of future generations to meet theirs.',
        ieltsExample: 'Sustainable development meets present needs without compromising the ability of future generations to meet theirs.',
        phrase: 'promote sustainable growth',
        warning: 'It has become a buzzword; try to pair it with specific nouns like "agriculture" or "development" to sound academic.',
        confusionWarning: 'It has become a buzzword; try to pair it with specific nouns like "agriculture" or "development" to sound academic.',
        useCases: ['urban planning', 'agriculture', 'business practices', 'economic growth'],
        mistake: {
          wrong: 'The car drives at a sustainable speed.',
          right: 'The city is investing in sustainable public transport.',
        },
        why: 'In IELTS, sustainable almost always refers to environmental or long-term economic viability.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'neutrality',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the state of not supporting or helping either side in a conflict, or (in environment) balancing emissions with removal',
        instant: 'net zero impact',
        clue: 'Use it in the phrase "carbon neutrality" when discussing goals to balance out emissions completely.',
        pattern: 'carbon neutrality / achieve neutrality',
        commonPattern: 'carbon neutrality / achieve neutrality',
        example: 'Many corporations have pledged to achieve carbon neutrality by the year 2050.',
        ieltsExample: 'Many corporations have pledged to achieve carbon neutrality by the year 2050.',
        phrase: 'strive for carbon neutrality',
        warning: 'On its own, neutrality means taking no side. Always pair it with "carbon" in environmental essays.',
        confusionWarning: 'On its own, neutrality means taking no side. Always pair it with "carbon" in environmental essays.',
        useCases: ['corporate goals', 'government targets', 'climate accords', 'emission reduction'],
        mistake: {
          wrong: 'The factory achieved neutrality by turning off its machines.',
          right: 'The factory achieved carbon neutrality by planting trees to offset its emissions.',
        },
        why: 'Carbon neutrality involves balancing emissions with removal, not just stopping production.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'decarbonize',
        part: 'verb',
        grammarRole: 'Verb',
        meaning: 'to reduce the amount of gaseous carbon compounds released in or as a result of an environment or process',
        instant: 'remove carbon emissions',
        clue: 'Use it to describe the transition away from fossil fuels in industries like transport or energy.',
        pattern: 'decarbonize the economy / decarbonizing sectors',
        commonPattern: 'decarbonize the economy / decarbonizing sectors',
        example: 'Electric vehicles are essential for decarbonizing the transport sector.',
        ieltsExample: 'Electric vehicles are essential for decarbonizing the transport sector.',
        phrase: 'efforts to decarbonize',
        warning: 'It is a specific technical term. Use it only when discussing the removal of carbon emissions from a system.',
        confusionWarning: 'It is a specific technical term. Use it only when discussing the removal of carbon emissions from a system.',
        useCases: ['transportation', 'energy sector', 'industrial processes', 'national policy'],
        mistake: {
          wrong: 'We need to decarbonize the dirty river.',
          right: 'We need to decarbonize our energy grid.',
        },
        why: 'Decarbonize refers specifically to greenhouse gas emissions, not general water or soil pollution.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Talking about energy sources like wind and solar?', answer: 'Use renewable.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Discussing practices that don\\'t harm the future?', answer: 'Use sustainable.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Talking about achieving net-zero emissions?', answer: 'Use neutrality (carbon neutrality).', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Describing the process of shifting away from fossil fuels?', answer: 'Use decarbonize.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'To combat climate change, many countries are investing heavily in ______ energy sources like wind and solar power.',
        options: ['sustainable', 'renewable', 'neutrality'],
        correct: 'renewable',
        explanation: 'Energy sources that naturally replenish are called renewable.',
      },
      {
        prompt: 'Replacing gas-powered cars with electric vehicles is a key step to ______ the transportation sector.',
        options: ['decarbonize', 'sustain', 'neutralize'],
        correct: 'decarbonize',
        explanation: 'Decarbonize specifically means removing carbon emissions from a process or sector.',
      },
      {
        prompt: 'Which phrase describes an economy where resources are reused and waste is minimized over the long term?',
        options: ['renewable economy', 'sustainable development', 'carbon neutrality'],
        correct: 'sustainable development',
        explanation: 'Sustainable development ensures long-term viability without depleting resources.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Renewable** = energy that renews itself. **Sustainable** = systems that can sustain themselves long-term.',
    },
    contrastTip: {
      title: 'Renewable vs Sustainable',
      text: '**Renewable** specifically describes resources (like sunlight). **Sustainable** describes broader practices (like sustainable agriculture or sustainable living).',
    },
    applyPrompt: 'Explain how investing in green technology can benefit both the environment and the economy.',
    applyHint: 'Aim to use: **renewable**, **sustainable**, and **decarbonize**.',
    modelAnswer:
      'Investing in renewable energy not only helps to decarbonize the economy, but it also creates sustainable jobs that ensure long-term economic stability while protecting the environment.',
    modelAnswerSegments: [
      { text: 'Investing in ' },
      { text: 'renewable', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' energy not only helps to ' },
      { text: 'decarbonize', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' the economy, but it also creates ' },
      { text: 'sustainable', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' jobs that ensure long-term economic stability while protecting the environment.' },
    ],
    modelBreakdown: [
      { term: 'renewable', text: 'describing the type of energy.' },
      { term: 'decarbonize', text: 'referring to the removal of carbon emissions.' },
      { term: 'sustainable', text: 'describing long-lasting, environmentally friendly jobs.' },
    ],
    heroWordBubbles: [
      { label: 'renewable', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'sustainable', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'neutrality', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'decarbonize', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Solution Match', subtitle: 'Connect green technologies with their environmental benefits.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Upgrade', subtitle: 'Replace basic words like "good for nature" with advanced vocabulary.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Collocation Check', subtitle: 'Pair sustainable and renewable with the correct nouns.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Concept Explanation', subtitle: 'Explain what carbon neutrality means in simple terms.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss what your city is doing to be more sustainable.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
`;

const path = 'src/data/deepVocabularyLessons.ts';
let content = fs.readFileSync(path, 'utf8');

// find the last bracket
const lastIndex = content.lastIndexOf('};');
const newContent = content.slice(0, lastIndex) + lesson1 + content.slice(lastIndex);

fs.writeFileSync(path, newContent);
console.log('Batch 9 added.');
