const fs = require('fs');

const lesson1 = `
  'pollution-environmental-degradation': {
    lessonNumber: '21',
    title: 'Pollution & Environmental Degradation',
    subtitle: 'Discuss pollution types and their environmental damage.',
    level: 'Band 6.5 - 8.0',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 21',
    sidebarLessonLabel: 'Lesson 21',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master 25 pollution and degradation terms',
      'Discuss environmental problems precisely',
      'Differentiate between pollution types'
    ],
    words: [
      {
        word: 'emission',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the production and discharge of something, especially gas or radiation',
        instant: 'gas discharge',
        clue: 'Use it when talking about gases coming from factories or vehicles.',
        pattern: 'vehicle emissions / reduce emissions',
        commonPattern: 'vehicle emissions / reduce emissions',
        example: 'Air pollution from vehicle emissions contributes to respiratory diseases.',
        ieltsExample: 'Air pollution from vehicle emissions contributes to respiratory diseases.',
        phrase: 'cut greenhouse gas emissions',
        warning: 'It refers specifically to airborne pollutants, not liquid waste (which is effluent).',
        confusionWarning: 'It refers specifically to airborne pollutants, not liquid waste (which is effluent).',
        useCases: ['air pollution', 'climate change', 'transport', 'industry'],
        mistake: {
          wrong: 'The factory poured its emissions into the river.',
          right: 'The factory poured its effluent into the river, and its emissions into the air.',
        },
        why: 'Emissions are released into the air; liquid waste released into water is effluent.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'effluent',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'liquid waste or sewage discharged into a river or the sea',
        instant: 'liquid waste',
        clue: 'Use it when talking about industrial factories polluting water bodies.',
        pattern: 'industrial effluent / untreated effluent',
        commonPattern: 'industrial effluent / untreated effluent',
        example: 'Industrial effluent contaminates waterways and harms aquatic life.',
        ieltsExample: 'Industrial effluent contaminates waterways and harms aquatic life.',
        phrase: 'discharge of toxic effluent',
        warning: 'It only applies to liquid waste, never solid waste or air pollution.',
        confusionWarning: 'It only applies to liquid waste, never solid waste or air pollution.',
        useCases: ['water pollution', 'industrial waste', 'marine life', 'environmental regulations'],
        mistake: {
          wrong: 'The factory smoke is dangerous effluent.',
          right: 'The factory pumps dangerous effluent into the lake.',
        },
        why: 'Effluent refers exclusively to liquid waste.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'degradation',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the condition or process of degrading or being degraded (especially of the environment)',
        instant: 'worsening condition',
        clue: 'Use it when describing the long-term deterioration of soil, land, or the overall environment.',
        pattern: 'environmental degradation / soil degradation',
        commonPattern: 'environmental degradation / soil degradation',
        example: 'Soil degradation reduces agricultural productivity and threatens global food security.',
        ieltsExample: 'Soil degradation reduces agricultural productivity and threatens global food security.',
        phrase: 'halt environmental degradation',
        warning: 'It means a slow decline in quality, not a sudden destruction.',
        confusionWarning: 'It means a slow decline in quality, not a sudden destruction.',
        useCases: ['agriculture', 'deforestation', 'urban sprawl', 'conservation'],
        mistake: {
          wrong: 'The bomb caused the degradation of the building.',
          right: 'Poor farming practices caused the degradation of the soil.',
        },
        why: 'Degradation refers to a gradual decline in quality or condition, especially environmental.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'contaminate',
        part: 'verb',
        grammarRole: 'Verb',
        meaning: 'make (something) impure by exposure to or addition of a poisonous or polluting substance',
        instant: 'make impure/toxic',
        clue: 'Use it when talking about pollution making something unsafe to use (like drinking water).',
        pattern: 'contaminate the water supply / heavily contaminated',
        commonPattern: 'contaminate the water supply / heavily contaminated',
        example: 'Groundwater can become contaminated by agricultural runoff containing pesticides.',
        ieltsExample: 'Groundwater can become contaminated by agricultural runoff containing pesticides.',
        phrase: 'risk of contaminating',
        warning: 'It implies introducing a harmful substance, not just making something messy.',
        confusionWarning: 'It implies introducing a harmful substance, not just making something messy.',
        useCases: ['water quality', 'food safety', 'industrial accidents', 'waste disposal'],
        mistake: {
          wrong: 'The leaves contaminated the swimming pool.',
          right: 'Chemical waste contaminated the river.',
        },
        why: 'Contaminate implies toxins or impurities, not just physical debris like leaves.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Talking about gases from cars or factories?', answer: 'Use emission.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Talking about liquid waste going into water?', answer: 'Use effluent.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Describing the slow decline of the environment?', answer: 'Use degradation.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Talking about making water or soil toxic?', answer: 'Use contaminate.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'Factories must be heavily fined if they release toxic ______ into local rivers.',
        options: ['emissions', 'degradation', 'effluent'],
        correct: 'effluent',
        explanation: 'Effluent specifically refers to liquid waste discharged into water.',
      },
      {
        prompt: 'The gradual ______ of the soil means that farmers can no longer grow crops there.',
        options: ['degradation', 'effluent', 'contaminate'],
        correct: 'degradation',
        explanation: 'Degradation refers to the decline in quality or condition over time.',
      },
      {
        prompt: 'To improve air quality in cities, governments must reduce vehicle ______.',
        options: ['effluent', 'emissions', 'degradation'],
        correct: 'emissions',
        explanation: 'Emissions refer to gases discharged into the air.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Emissions** go up (into the air). **Effluent** flows out (into the water).',
    },
    contrastTip: {
      title: 'Pollute vs Contaminate',
      text: '**Pollute** is general (air pollution, noise pollution). **Contaminate** is specific—it means introducing a toxic or impure substance into something clean (like water or food).',
    },
    applyPrompt: 'Discuss the different ways industrial activities harm the environment.',
    applyHint: 'Aim to use: **emissions**, **effluent**, and **degradation**.',
    modelAnswer:
      'Industrial activities drive environmental degradation on multiple fronts; factories release harmful emissions into the atmosphere while simultaneously discharging toxic effluent into nearby waterways.',
    modelAnswerSegments: [
      { text: 'Industrial activities drive environmental ' },
      { text: 'degradation', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ' on multiple fronts; factories release harmful ' },
      { text: 'emissions', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' into the atmosphere while simultaneously discharging toxic ' },
      { text: 'effluent', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' into nearby waterways, thereby ' },
      { text: 'contaminating', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' the local water supply.' },
    ],
    modelBreakdown: [
      { term: 'degradation', text: 'describing the overall decline in environmental quality.' },
      { term: 'emissions', text: 'referring to the air pollution.' },
      { term: 'effluent', text: 'referring to the liquid water pollution.' },
      { term: 'contaminating', text: 'describing the poisoning of the water.' },
    ],
    heroWordBubbles: [
      { label: 'emission', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'effluent', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'degradation', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'contaminate', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Word Builder', subtitle: 'Practice using different forms of the word degrade.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'List causes of soil degradation.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Match', subtitle: 'Differentiate between emissions and effluent.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of the word contaminate.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Talk about a pollution problem in your country.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
  'conservation-wildlife-protection': {
    lessonNumber: '22',
    title: 'Conservation & Wildlife Protection',
    subtitle: 'Discuss endangered species and habitat protection.',
    level: 'Band 6.5 - 8.0',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 22',
    sidebarLessonLabel: 'Lesson 22',
    deepLessonProgress: 0,
    learningOutcomes: [
      'Master 25 conservation and wildlife terms',
      'Discuss endangered species and protection efforts',
      'Use ecological vocabulary accurately'
    ],
    words: [
      {
        word: 'endangered',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: '(of a species) seriously at risk of extinction',
        instant: 'at risk of dying out',
        clue: 'Use it when talking about animals or plants that might disappear forever.',
        pattern: 'endangered species / critically endangered',
        commonPattern: 'endangered species / critically endangered',
        example: 'Endangered species face extinction without immediate conservation efforts.',
        ieltsExample: 'Endangered species face extinction without immediate conservation efforts.',
        phrase: 'protect endangered habitats',
        warning: 'It means "in danger of going extinct," not just "in danger" from a localized threat.',
        confusionWarning: 'It means "in danger of going extinct," not just "in danger" from a localized threat.',
        useCases: ['wildlife protection', 'biodiversity', 'extinction', 'zoos'],
        mistake: {
          wrong: 'The cat in the tree is endangered.',
          right: 'The Siberian tiger is an endangered species.',
        },
        why: 'Endangered applies to an entire species at risk of extinction, not an individual animal in a dangerous situation.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'poaching',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the illegal hunting, capturing, or killing of wild animals',
        instant: 'illegal hunting',
        clue: 'Use it when talking about people killing animals like elephants or rhinos illegally.',
        pattern: 'anti-poaching measures / illegal poaching',
        commonPattern: 'anti-poaching measures / illegal poaching',
        example: 'Poaching remains a significant threat to wildlife populations in Africa.',
        ieltsExample: 'Poaching remains a significant threat to wildlife populations in Africa.',
        phrase: 'combat the poaching of',
        warning: 'Do not confuse it with legal hunting; poaching is always illegal.',
        confusionWarning: 'Do not confuse it with legal hunting; poaching is always illegal.',
        useCases: ['wildlife crime', 'animal rights', 'black market', 'conservation'],
        mistake: {
          wrong: 'The government allows poaching during the winter.',
          right: 'The government has cracked down on elephant poaching.',
        },
        why: 'Poaching by definition is an illegal act, so a government would not allow it.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'conservation',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'preservation, protection, or restoration of the natural environment and wildlife',
        instant: 'environmental protection',
        clue: 'Use it when discussing efforts to save nature or resources (like water or energy).',
        pattern: 'conservation efforts / wildlife conservation',
        commonPattern: 'conservation efforts / wildlife conservation',
        example: 'Conservation efforts are essential to protect biodiversity and natural habitats.',
        ieltsExample: 'Conservation efforts are essential to protect biodiversity and natural habitats.',
        phrase: 'promote energy conservation',
        warning: 'It means protecting and managing natural resources, while preservation means keeping something exactly as it is without human interference.',
        confusionWarning: 'It means protecting and managing natural resources, while preservation means keeping something exactly as it is without human interference.',
        useCases: ['environmental policy', 'national parks', 'resource management', 'wildlife'],
        mistake: {
          wrong: 'He works in the conservation of old coins.',
          right: 'He works in marine conservation.',
        },
        why: 'While one can "conserve" items, "conservation" as a noun almost always refers to the environment or natural resources.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'habitat',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the natural home or environment of an animal, plant, or other organism',
        instant: 'natural home',
        clue: 'Use it instead of "home" when talking about where wild animals live.',
        pattern: 'habitat destruction / natural habitat',
        commonPattern: 'habitat destruction / natural habitat',
        example: 'Habitat destruction due to urban sprawl is the leading cause of species extinction.',
        ieltsExample: 'Habitat destruction due to urban sprawl is the leading cause of species extinction.',
        phrase: 'loss of natural habitat',
        warning: 'Do not use it for human homes unless speaking metaphorically or ecologically.',
        confusionWarning: 'Do not use it for human homes unless speaking metaphorically or ecologically.',
        useCases: ['deforestation', 'urbanization', 'ecology', 'animal behavior'],
        mistake: {
          wrong: 'My house is a nice habitat for my family.',
          right: 'The rainforest is a vital habitat for thousands of species.',
        },
        why: 'Habitat is a scientific term for the natural environment of flora and fauna.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Describing an animal that might go extinct?', answer: 'Use endangered.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Talking about people illegally killing wild animals?', answer: 'Use poaching.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Discussing the protection of nature or resources?', answer: 'Use conservation.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Referring to the natural environment where an animal lives?', answer: 'Use habitat.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'The government has created new national parks to support wildlife ______.',
        options: ['poaching', 'conservation', 'endangered'],
        correct: 'conservation',
        explanation: 'Conservation refers to the protection and management of the environment.',
      },
      {
        prompt: 'Rhinos are heavily hunted for their horns, making ______ a major threat to their survival.',
        options: ['poaching', 'habitat', 'conservation'],
        correct: 'poaching',
        explanation: 'Poaching is the illegal hunting of animals.',
      },
      {
        prompt: 'When forests are cut down, animals lose their natural ______ and may die out.',
        options: ['conservation', 'habitat', 'endangered'],
        correct: 'habitat',
        explanation: 'A habitat is the natural home or environment of an animal.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Poaching** steals animals. **Conservation** saves them.',
    },
    contrastTip: {
      title: 'Hunting vs Poaching',
      text: '**Hunting** can be legal and regulated. **Poaching** is always illegal.',
    },
    applyPrompt: 'Discuss the main threats to wild animals and what can be done to protect them.',
    applyHint: 'Aim to use: **endangered**, **poaching**, **habitat**, and **conservation**.',
    modelAnswer:
      'Many species have become endangered due to illegal poaching and habitat destruction, meaning strict conservation efforts are urgently needed to protect them.',
    modelAnswerSegments: [
      { text: 'Many species have become ' },
      { text: 'endangered', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' due to illegal ' },
      { text: 'poaching', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' and ' },
      { text: 'habitat', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' destruction, meaning strict ' },
      { text: 'conservation', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: ' efforts are urgently needed to protect them.' },
    ],
    modelBreakdown: [
      { term: 'endangered', text: 'describing the risk of extinction.' },
      { term: 'poaching', text: 'referring to the illegal killing of animals.' },
      { term: 'habitat', text: 'referring to the animals\\' natural homes.' },
      { term: 'conservation', text: 'describing the actions needed to save them.' },
    ],
    heroWordBubbles: [
      { label: 'endangered', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'poaching', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'conservation', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'habitat', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Solution Match', subtitle: 'Connect conservation strategies to specific threats.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Upgrade', subtitle: 'Replace "animals in danger" with advanced vocabulary.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Collocation Check', subtitle: 'Identify common collocations for the word habitat.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Concept Explanation', subtitle: 'Explain why conservation is important for humanity.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss an endangered animal from your region.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
`;

const path = 'src/data/deepVocabularyLessons.ts';
let content = fs.readFileSync(path, 'utf8');

// find the last bracket
const lastIndex = content.lastIndexOf('};');
const newContent = content.slice(0, lastIndex) + lesson1 + content.slice(lastIndex);

fs.writeFileSync(path, newContent);
console.log('Batch 10 added.');
