const fs = require('fs');

const lesson1 = `
  'educational-philosophy-teaching-methods': {
    lessonNumber: '17',
    title: 'Educational Philosophy & Teaching Methods',
    subtitle: 'Discuss teaching methodologies and learning theories confidently.',
    level: 'Band 7.0 - 8.0',
    estimatedTime: '10-12 min',
    categoryLabel: 'Advanced Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 17',
    sidebarLessonLabel: 'Lesson 17',
    deepLessonProgress: 15,
    learningOutcomes: [
      'Master advanced education terms for Band 7-8 writing',
      'Discuss teaching methodologies and learning theories confidently',
      'Analyze educational approaches with sophisticated vocabulary'
    ],
    words: [
      {
        word: 'pedagogical',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: 'relating to teaching methods and practices',
        instant: 'related to teaching methods',
        clue: 'Use it when discussing the specific methods and approaches teachers use in the classroom.',
        pattern: 'pedagogical approach / pedagogical methods',
        commonPattern: 'pedagogical approach / pedagogical methods',
        example: 'Pedagogical approaches vary significantly across different cultures and educational systems.',
        ieltsExample: 'Pedagogical approaches vary significantly across different cultures and educational systems.',
        phrase: 'adopt a new pedagogical approach',
        warning: 'Do not use it simply to mean "educational" in a general sense; it specifically refers to the art or science of teaching.',
        confusionWarning: 'Do not use it simply to mean "educational" in a general sense; it specifically refers to the art or science of teaching.',
        useCases: ['teaching methods', 'curriculum design', 'teacher training', 'educational reform'],
        mistake: {
          wrong: 'The school needs better pedagogical facilities like labs.',
          right: 'The school needs better educational facilities like labs.',
        },
        why: 'It specifically refers to the method of teaching, not the general environment or resources.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'formative',
        part: 'adjective',
        grammarRole: 'Adjective',
        meaning: 'serving to form something, especially having a profound and lasting influence on a person\\'s development',
        instant: 'shaping development over time',
        clue: 'Use it when describing assessments or experiences that help shape a student\\'s ongoing learning process.',
        pattern: 'formative assessment / formative years',
        commonPattern: 'formative assessment / formative years',
        example: 'Formative assessment provides ongoing feedback during the learning process rather than just a final grade.',
        ieltsExample: 'Formative assessment provides ongoing feedback during the learning process rather than just a final grade.',
        phrase: 'during their formative years',
        warning: 'Do not confuse it with summative, which refers to final evaluations at the end of a course.',
        confusionWarning: 'Do not confuse it with summative, which refers to final evaluations at the end of a course.',
        useCases: ['assessment', 'child development', 'ongoing feedback', 'early education'],
        mistake: {
          wrong: 'The final exam is a highly formative test.',
          right: 'The final exam is a highly summative test.',
        },
        why: 'Formative refers to the process of forming or developing, while summative refers to the end result.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'scaffolding',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'a teaching method that provides temporary support to help a student master a new skill or concept',
        instant: 'temporary teaching support',
        clue: 'Use it to describe how teachers break learning into smaller, manageable chunks with support that is gradually removed.',
        pattern: 'provide scaffolding / instructional scaffolding',
        commonPattern: 'provide scaffolding / instructional scaffolding',
        example: 'Effective teachers use scaffolding to help students tackle complex academic texts independently.',
        ieltsExample: 'Effective teachers use scaffolding to help students tackle complex academic texts independently.',
        phrase: 'offer adequate scaffolding',
        warning: 'It is a metaphorical term in education, so do not confuse it with physical construction equipment.',
        confusionWarning: 'It is a metaphorical term in education, so do not confuse it with physical construction equipment.',
        useCases: ['teaching strategies', 'skill building', 'student support', 'lesson planning'],
        mistake: {
          wrong: 'The teacher built scaffolding around the classroom.',
          right: 'The teacher provided scaffolding to support the students\\' learning.',
        },
        why: 'In an educational context, scaffolding is a conceptual support structure, not a physical one.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'metacognition',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'awareness and understanding of one\\'s own thought processes; thinking about thinking',
        instant: 'thinking about thinking',
        clue: 'Use it when discussing students\\' ability to monitor, evaluate, and plan their own learning strategies.',
        pattern: 'develop metacognition / metacognitive skills',
        commonPattern: 'develop metacognition / metacognitive skills',
        example: 'Developing metacognitive skills enables students to become more effective, independent learners.',
        ieltsExample: 'Developing metacognitive skills enables students to become more effective, independent learners.',
        phrase: 'foster metacognitive awareness',
        warning: 'It is a highly academic term; use it only when specifically referring to self-regulated learning and reflection.',
        confusionWarning: 'It is a highly academic term; use it only when specifically referring to self-regulated learning and reflection.',
        useCases: ['self-reflection', 'study strategies', 'independent learning', 'cognitive development'],
        mistake: {
          wrong: 'Students need metacognition to memorize facts quickly.',
          right: 'Students need metacognitive skills to evaluate which memorization strategies work best for them.',
        },
        why: 'Metacognition is about evaluating the strategy itself, not just the act of learning the content.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Talking about teaching methods?', answer: 'Use pedagogical.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Discussing ongoing feedback to shape learning?', answer: 'Use formative.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Describing temporary support given to a learner?', answer: 'Use scaffolding.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Referring to a student reflecting on how they learn?', answer: 'Use metacognition.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'The university is updating its ______ approaches to include more interactive, student-centered activities.',
        options: ['pedagogical', 'metacognitive', 'formative'],
        correct: 'pedagogical',
        explanation: 'Pedagogical refers directly to teaching methods and approaches.',
      },
      {
        prompt: 'By reflecting on their mistakes and adjusting their study habits, students develop strong ______ skills.',
        options: ['formative', 'metacognitive', 'scaffolding'],
        correct: 'metacognitive',
        explanation: 'Reflecting on one\\'s own learning and thinking process is metacognition.',
      },
      {
        prompt: 'Which word best describes a quiz that doesn\\'t count for a grade but helps the teacher see what students need to review?',
        options: ['pedagogical', 'scaffolding', 'formative'],
        correct: 'formative',
        explanation: 'Formative assessments provide ongoing feedback to shape learning, rather than a final evaluation.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Pedagogy** = how to teach. **Metacognition** = how you think about learning.',
    },
    contrastTip: {
      title: 'Formative vs Summative',
      text: '**Formative** assessment shapes learning while it\\'s happening. **Summative** assessment measures learning at the very end.',
    },
    applyPrompt: 'Discuss the benefits of giving students continuous feedback and teaching them how to evaluate their own learning progress.',
    applyHint: 'Aim to use: **pedagogical**, **formative**, and **metacognition**.',
    modelAnswer:
      'A modern pedagogical approach emphasizes formative assessment, which provides students with ongoing feedback and helps them develop essential metacognitive skills to direct their own learning.',
    modelAnswerSegments: [
      { text: 'A modern ' },
      { text: 'pedagogical', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' approach emphasizes ' },
      { text: 'formative', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' assessment, which provides students with ongoing feedback and helps them develop essential ' },
      { text: 'metacognitive', highlightClass: 'rounded bg-emerald-100 px-1 text-emerald-900' },
      { text: ' skills to direct their own learning.' },
    ],
    modelBreakdown: [
      { term: 'pedagogical', text: 'describes the teaching approach.' },
      { term: 'formative', text: 'describes assessment used for feedback, not final grades.' },
      { term: 'metacognitive', text: 'highlights students thinking about their own learning.' },
    ],
    heroWordBubbles: [
      { label: 'pedagogical', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'formative', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'scaffolding', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'metacognition', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Methodology Match', subtitle: 'Match teaching strategies with their academic terms.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Assessment Sort', subtitle: 'Categorize tests as formative or summative.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Task 2 Upgrade', subtitle: 'Replace basic teaching words with pedagogical vocabulary.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Error Correction', subtitle: 'Fix misuses of advanced educational terms.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Describe a good teacher using 3 advanced terms.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
  'education-policy-systemic-reform': {
    lessonNumber: '18',
    title: 'Education Policy & Systemic Reform',
    subtitle: 'Analyze systemic educational challenges and reforms with precision.',
    level: 'Band 8.0 - 9.0',
    estimatedTime: '10-12 min',
    categoryLabel: 'Expert Vocabulary',
    lessonBadgeLabel: 'Vocabulary · Lesson 18',
    sidebarLessonLabel: 'Lesson 18',
    deepLessonProgress: 10,
    learningOutcomes: [
      'Master sophisticated education policy terms for Band 8-9',
      'Analyze systemic educational challenges with precision',
      'Discuss global education trends and reforms authoritatively'
    ],
    words: [
      {
        word: 'equity',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'fairness and justice in educational access and outcomes, recognizing that different students need different resources',
        instant: 'fairness addressing specific needs',
        clue: 'Use it when discussing policies that aim to level the playing field for disadvantaged students.',
        pattern: 'educational equity / promote equity',
        commonPattern: 'educational equity / promote equity',
        example: 'Educational equity requires addressing the systemic barriers that disadvantage students from low-income backgrounds.',
        ieltsExample: 'Educational equity requires addressing the systemic barriers that disadvantage students from low-income backgrounds.',
        phrase: 'strive for educational equity',
        warning: 'Do not confuse it with equality; equality means everyone gets the same, equity means everyone gets what they need to succeed.',
        confusionWarning: 'Do not confuse it with equality; equality means everyone gets the same, equity means everyone gets what they need to succeed.',
        useCases: ['policy reform', 'resource allocation', 'social justice', 'access to education'],
        mistake: {
          wrong: 'Giving all schools the exact same budget ensures equity.',
          right: 'Giving underfunded schools more resources to catch up ensures equity.',
        },
        why: 'Equity implies fairness in outcomes, which often requires unequal distribution of resources based on need.',
        accent: {
          border: 'border-indigo-200',
          surface: 'bg-indigo-50/70',
          badge: 'bg-indigo-100 text-indigo-700',
          heading: 'text-indigo-700',
          ring: 'ring-indigo-100',
          dot: 'bg-blue-600',
        },
      },
      {
        word: 'accountability',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the requirement that educational institutions demonstrate and take responsibility for their performance and student outcomes',
        instant: 'responsibility for outcomes',
        clue: 'Use it when discussing standardized testing, school rankings, or government oversight of education.',
        pattern: 'accountability measures / hold accountable',
        commonPattern: 'accountability measures / hold accountable',
        example: 'Strict accountability measures hold schools responsible for student performance, often tying funding to test scores.',
        ieltsExample: 'Strict accountability measures hold schools responsible for student performance, often tying funding to test scores.',
        phrase: 'implement accountability systems',
        warning: 'It often carries a negative connotation among educators when linked strictly to standardized test scores.',
        confusionWarning: 'It often carries a negative connotation among educators when linked strictly to standardized test scores.',
        useCases: ['standardized testing', 'school performance', 'government policy', 'educational funding'],
        mistake: {
          wrong: 'Students need accountability to do their homework.',
          right: 'Schools face increased accountability from the government regarding their graduation rates.',
        },
        why: 'In education policy, accountability typically refers to institutional or teacher responsibility, not student homework habits.',
        accent: {
          border: 'border-violet-200',
          surface: 'bg-violet-50/70',
          badge: 'bg-violet-100 text-violet-700',
          heading: 'text-violet-700',
          ring: 'ring-violet-100',
          dot: 'bg-violet-600',
        },
      },
      {
        word: 'stratification',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the arrangement or division of students into different levels or social classes based on their educational background or ability',
        instant: 'division into hierarchical layers',
        clue: 'Use it when discussing how education systems can separate people into different societal groups, often perpetuating inequality.',
        pattern: 'educational stratification / social stratification',
        commonPattern: 'educational stratification / social stratification',
        example: 'Educational stratification can reproduce and perpetuate social inequalities across generations.',
        ieltsExample: 'Educational stratification can reproduce and perpetuate social inequalities across generations.',
        phrase: 'reduce systemic stratification',
        warning: 'It is a complex sociological term; use it specifically when discussing inequality and tracking/streaming in schools.',
        confusionWarning: 'It is a complex sociological term; use it specifically when discussing inequality and tracking/streaming in schools.',
        useCases: ['social inequality', 'streaming/tracking', 'private vs public education', 'class divisions'],
        mistake: {
          wrong: 'The school uses stratification to organize the library books.',
          right: 'The policy of streaming students by ability can lead to educational stratification.',
        },
        why: 'Stratification refers to hierarchical layering of people or society, not organizing objects.',
        accent: {
          border: 'border-amber-200',
          surface: 'bg-amber-50/80',
          badge: 'bg-amber-100 text-amber-800',
          heading: 'text-amber-800',
          ring: 'ring-amber-100',
          dot: 'bg-amber-500',
        },
      },
      {
        word: 'attainment',
        part: 'noun',
        grammarRole: 'Noun',
        meaning: 'the action or fact of achieving a specific educational level or qualification',
        instant: 'level of education achieved',
        clue: 'Use it to describe the highest degree or level of schooling a person has completed.',
        pattern: 'educational attainment / level of attainment',
        commonPattern: 'educational attainment / level of attainment',
        example: 'Research shows that higher educational attainment correlates strongly with increased lifetime earnings.',
        ieltsExample: 'Research shows that higher educational attainment correlates strongly with increased lifetime earnings.',
        phrase: 'raise overall attainment levels',
        warning: 'Do not confuse it with achievement; attainment is about the credential earned, while achievement often refers to how well the student learned.',
        confusionWarning: 'Do not confuse it with achievement; attainment is about the credential earned, while achievement often refers to how well the student learned.',
        useCases: ['statistics', 'employment outcomes', 'graduation rates', 'demographic studies'],
        mistake: {
          wrong: 'He felt a great sense of attainment when he finally understood the math problem.',
          right: 'His high level of educational attainment opened many career opportunities.',
        },
        why: 'Attainment in this academic context specifically refers to the completion of formal education levels.',
        accent: {
          border: 'border-emerald-200',
          surface: 'bg-emerald-50/70',
          badge: 'bg-emerald-100 text-emerald-700',
          heading: 'text-emerald-700',
          ring: 'ring-emerald-100',
          dot: 'bg-emerald-600',
        },
      },
    ],
    quickDecisionRules: [
      { cue: 'Discussing fairness that addresses different needs?', answer: 'Use equity.', tone: 'border-indigo-200 bg-indigo-50/70 text-indigo-950' },
      { cue: 'Talking about schools being responsible for test scores?', answer: 'Use accountability.', tone: 'border-violet-200 bg-violet-50/70 text-violet-950' },
      { cue: 'Describing how education divides society into different levels?', answer: 'Use stratification.', tone: 'border-amber-200 bg-amber-50/80 text-amber-950' },
      { cue: 'Referring to the highest degree a person has earned?', answer: 'Use attainment.', tone: 'border-emerald-200 bg-emerald-50/70 text-emerald-950' },
    ],
    checks: [
      {
        prompt: 'The government aims to improve social mobility by raising the educational ______ of students from disadvantaged backgrounds.',
        options: ['accountability', 'stratification', 'attainment'],
        correct: 'attainment',
        explanation: 'Attainment refers to the level of educational qualifications achieved by the students.',
      },
      {
        prompt: 'Critics argue that high-stakes testing places unfair ______ on teachers for factors outside their control.',
        options: ['equity', 'accountability', 'stratification'],
        correct: 'accountability',
        explanation: 'Holding teachers and schools responsible for results is referred to as accountability.',
      },
      {
        prompt: 'Which word best describes a system that unintentionally separates rich and poor students into completely different quality schools?',
        options: ['attainment', 'stratification', 'equity'],
        correct: 'stratification',
        explanation: 'Stratification is the division of groups into hierarchical societal layers.',
      },
    ],
    memoryTip: {
      title: 'Quick memory trick',
      text: '**Equity** = fairness based on need. **Attainment** = the credential you get at the end.',
    },
    contrastTip: {
      title: 'Equality vs Equity',
      text: '**Equality** is giving every school $10,000. **Equity** is giving struggling schools $15,000 and thriving schools $5,000 so everyone can succeed equally.',
    },
    applyPrompt: 'Argue whether holding schools strictly responsible for test scores helps or harms fairness in the education system.',
    applyHint: 'Aim to use: **accountability**, **equity**, and **stratification**.',
    modelAnswer:
      'While strict accountability measures aim to improve standards, they can sometimes harm educational equity by pushing underfunded schools to focus only on test preparation, thereby worsening social stratification.',
    modelAnswerSegments: [
      { text: 'While strict ' },
      { text: 'accountability', highlightClass: 'rounded bg-violet-100 px-1 text-violet-900' },
      { text: ' measures aim to improve standards, they can sometimes harm educational ' },
      { text: 'equity', highlightClass: 'rounded bg-indigo-100 px-1 text-indigo-900' },
      { text: ' by pushing underfunded schools to focus only on test preparation, thereby worsening social ' },
      { text: 'stratification', highlightClass: 'rounded bg-amber-100 px-1 text-amber-900' },
      { text: '.' },
    ],
    modelBreakdown: [
      { term: 'accountability', text: 'referencing the pressure on schools to perform.' },
      { term: 'equity', text: 'highlighting the lack of fairness for disadvantaged students.' },
      { term: 'stratification', text: 'describing the resulting divide in society.' },
    ],
    heroWordBubbles: [
      { label: 'equity', className: 'absolute left-3 top-5 z-10 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-indigo-100' },
      { label: 'accountability', className: 'absolute right-4 top-8 z-10 rounded-lg bg-violet-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-violet-100' },
      { label: 'stratification', className: 'absolute bottom-8 left-9 z-10 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-white shadow-lg shadow-amber-100' },
      { label: 'attainment', className: 'absolute bottom-11 right-7 z-10 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white shadow-lg shadow-emerald-100' },
    ],
    practiceCards: [
      { title: 'Policy Match', subtitle: 'Connect advanced policy terms with their definitions.', tone: 'text-blue-600 bg-blue-50' },
      { title: 'Task 2 Brainstorm', subtitle: 'Use policy vocabulary to write a paragraph on school funding.', tone: 'text-violet-600 bg-violet-50' },
      { title: 'Concept Check', subtitle: 'Explain the difference between equality and equity.', tone: 'text-orange-600 bg-orange-50' },
      { title: 'Fill the Blank', subtitle: 'Complete high-level academic sentences correctly.', tone: 'text-emerald-600 bg-emerald-50' },
      { title: 'Speaking Drill', subtitle: 'Discuss a problem with your country\\'s education system.', tone: 'text-indigo-600 bg-indigo-50' },
    ],
  },
`;

const path = 'src/data/deepVocabularyLessons.ts';
let content = fs.readFileSync(path, 'utf8');

// find the last bracket
const lastIndex = content.lastIndexOf('};');
const newContent = content.slice(0, lastIndex) + lesson1 + content.slice(lastIndex);

fs.writeFileSync(path, newContent);
console.log('Batch 8 added.');
